server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mrp2104?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    initial-size: 10
    max-active: 20
    max-idle: 8
    min-idle: 8
    type: com.alibaba.druid.pool.DruidDataSource
#  mvc:
#    view:
#      prefix: /
#      suffix: .jsp
mybatis:
  type-aliases-package: com.aty.domain
  mapper-locations: classpath:com/aty/dao/*Dao.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      aty:
        dao : debug
